eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true     # Register this client with Eureka server
    fetch-registry: true           # Fetch registry from Eureka
  instance:
    prefer-ip-address: true        # Use IP address instead of hostname
